version: '3.2'

services:

  emby:
    container_name: emby
    image: emby/embyserver
    restart: always
    environment:
      - PGID=1000
      - PUID=1000
    volumes:
      - emby-data:/var/lib/emby
      - $PWD/libraries/movies:/media/Movies
      - $PWD/libraries/music:/media/Music
      - $PWD/libraries/photos:/media/Photos
      - $PWD/libraries/tv:/media/TV
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:${EMBY_URL}
      - traefik.port=8096
      - traefik.protocol=http
      - traefik.frontend.headers.referrerPolicy=no-referrer
      - traefik.frontend.headers.customFrameOptionsValue=DENY
      - "traefik.frontend.headers.contentSecurityPolicy=default-src 'none'; child-src 'self'; font-src 'self' data: ; connect-src 'self' wss: ws: https://mb3admin.com https://github.com/MediaBrowser/; media-src 'self' blob: data: https://github.com/MediaBrowser/; manifest-src 'self'; base-uri 'none'; form-action 'self'; frame-ancestors 'self'; object-src 'none'; worker-src 'self' blob: ; script-src 'unsafe-inline' 'self' https://www.gstatic.com; img-src data: https: http: ; style-src 'unsafe-inline' 'self' https://fonts.googleapis.com/css"
      - traefik.frontend.headers.STSSeconds=315360000
      - traefik.frontend.headers.contentTypeNosniff=true
    networks:
      - proxy

networks:
  proxy:
    external: true
volumes:
  emby-data:
