version: '3.2'

services:
  emby:
    image: emby/embyserver
    restart: always
    volumes:
      - emby-data:/var/lib/emby
      - $PWD/libraries/movies:/media/Movies:ro
      - $PWD/libraries/music:/media/Music:ro
      - $PWD/libraries/photos:/media/Photos:ro
      - $PWD/libraries/tv:/media/TV:ro
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:emby.kevily.net
      - traefik.port=8096
      - traefik.protocol=http
      - traefik.frontend.headers.referrerPolicy=no-referrer
      - traefik.frontend.headers.customFrameOptionsValue=DENY
      - "traefik.frontend.headers.contentSecurityPolicy=default-src 'none'; child-src 'self'; font-src 'self' 'data:'; connect-src 'self' 'wss:' 'ws: https://mb3admin.com https://github.com/MediaBrowser/'; media-src 'self' 'blob:' 'data:' https://github.com/MediaBrowser/; manifest-src 'self'; base-uri 'none'; form-action 'self'; frame-ancestors 'self'; object-src 'none'; worker-src 'self' 'blob:'; script-src 'self' https://www.gstatic.com; img-src 'data:' 'https:' 'http:' ; style-src 'unsafe-inline' 'self' https://fonts.googleapis.com/css"
      - traefik.frontend.headers.STSSeconds=315360000
      - traefik.frontend.headers.contentTypeNosniff=true
    networks:
      - proxy        
networks:
  proxy:
    external: true
volumes:
  emby-data:
