version: '2'

services:
  emby:
    image: emby/embyserver
    restart: always
    volumes:
      - emby-data:/var/lib/emby
      - /mnt/md1/server/services/emby/libraries/movies:/media/Movies:ro
      - /mnt/md1/server/services/emby/libraries/music:/media/Music:ro
      - /mnt/md1/server/services/emby/libraries/photos:/media/Photos:ro
      - /mnt/md1/server/services/emby/libraries/tv:/media/TV:ro
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:emby.kevily.net
      - traefik.port=8096
      - traefik.protocol=http
    networks:
      - proxy        
networks:
  proxy:
    external: true
volumes:
  emby-data:
