version: '3.2'
services:
  transmission:
    container_name: transmission
    image: haugene/transmission-openvpn
    restart: always
    privileged: true
    environment:
      - "OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60"
      - OPENVPN_PROVIDER=CUSTOM
      - OPENVPN_USERNAME=a
      - OPENVPN_PASSWORD=a
      - LOCAL_NETWORK=10.0.0.0/24
    ports:
      - 9091:9091
    networks:
      - embynet
    volumes:
      - $PWD/transmission:/data
      - /etc/localtime:/etc/localtime:ro
      - $PWD/.vpn/config.ovpn:/etc/openvpn/custom/default.ovpn
      - $PWD/.vpn/auth.txt:/etc/openvpn/custom/auth.txt

  emby:
    container_name: emby
    image: emby/embyserver
    restart: always
    volumes:
      - emby-data:/var/lib/emby
      - $PWD/libraries/movies:/media/Movies:ro
      - $PWD/libraries/music:/media/Music:ro
      - $PWD/libraries/photos:/media/Photos:ro
      - $PWD/libraries/tv:/media/TV:ro
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:emby.kevily.net
      - traefik.port=8096
      - traefik.protocol=http
      - traefik.frontend.headers.referrerPolicy=no-referrer
      - traefik.frontend.headers.customFrameOptionsValue=DENY
      - "traefik.frontend.headers.contentSecurityPolicy=default-src 'none'; child-src 'self'; font-src 'self' data: ; connect-src 'self' wss: ws: https://mb3admin.com https://github.com/MediaBrowser/; media-src 'self' blob: data: https://github.com/MediaBrowser/; manifest-src 'self'; base-uri 'none'; form-action 'self'; frame-ancestors 'self'; object-src 'none'; worker-src 'self' blob: ; script-src 'unsafe-inline' 'self' https://www.gstatic.com; img-src data: https: http: ; style-src 'unsafe-inline' 'self' https://fonts.googleapis.com/css"
      - traefik.frontend.headers.STSSeconds=315360000
      - traefik.frontend.headers.contentTypeNosniff=true
    networks:
      - proxy

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    restart: always
    environment:
      - TZ=America/New_York
      - PUID=1000
      - PGID=1000
    ports:
      - 8989:8989
    networks:
      - embynet
    volumes:
      - $PWD/config/sonarr:/config
      - $PWD/libraries/tv:/tv
      - $PWD/transmission/completed:/downloads

  radarr:
    container_name: radarr
    image: linuxserver/radarr
    restart: always
    ports:
      - 7878:7878
    environment:
      - TZ=Europe/London
      - PUID=1000
      - PGID=1000
    networks:
      - embynet
    volumes:
      - $PWD/config/radarr:/config
      - $PWD/libraries/movies:/movies
      - $PWD/transmission/completed:/downloads

  jackett:
    container_name: jackett
    image: linuxserver/jackett
    restart: always
    ports:
      - 9117:9117
    environment:
      - TZ=America/New_York
      - PGID=1000
      - PUID=1000
    networks:
      - embynet
    volumes:
      - $PWD/config/jackett:/config
      - $PWD/jackett/downloads:/downloads

networks:
  proxy:
    external: true
  embynet:
    driver: bridge
volumes:
  emby-data:
