debug = true

defaultEntryPoints = ["https", "http"]

[web]
address = ":8080"
[web.auth.basic]
users = ["admin:$apr1$KvRvraXJ$h.mAo8dQSFh/ViI.hmsh9/"]

[entryPoints]
[entryPoints.http]
address = ":80"
[entryPoints.http.redirect]
entryPoint = "https"
[entryPoints.https]
address = ":443"
[entryPoints.https.tls]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "kevily.net"
watch = true
exposedbydefault = false


[acme]
email = "kevinwmiller@protonmail.com"
storage = "/acme.json"
entryPoint = "https"
onHostRule = true
[acme.httpChallenge]
entryPoint = "http"
#[acme.dnsChallenge]
#provider = "namecheap"
#[[acme.domains]]
#main = "*.kevily.net"
#sans = ["dashboard.kevily.net", "cloud.kevily.net"]

