version: '2'

services:
  nextcloud-db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_DB=whatever
    env_file:
      - db.env
    networks:
      - nextcloud
  nextcloud:
    image: nextcloud
    restart: always
    volumes:
      - $PWD/data:/var/www/html
    environment:
      - POSTGRES_HOST=nextcloud-db
      - POSTGRES_DB=nextcloud
    env_file:
      - db.env
    depends_on:
      - nextcloud-db
    ports:
      - 3000:80
    networks:
      - proxy
      - nextcloud
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:${NEXTCLOUD_URL}
      - traefik.port=80
      - traefik.protocol=http
      - traefik.docker.network=proxy
      - traefik.frontend.headers.STSSeconds=315360000
networks:
  proxy:
    external: true
  nextcloud:
