version: '3'

services:
  nextcloud-db:
    image: postgres:alpine
    restart: always
    volumes:
      - /mnt/md1/services/nextcloud/postgres:/var/lib/postgresql/data
    env_file:
      - nextcloud/db.env
    networks:
      - cloud
  nextcloud:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - /mnt/md1/services/nextcloud/data:/var/www/html
    environment:
      - POSTGRES_HOST=nextcloud-db
    env_file:
      - nextcloud/db.env
    depends_on:
      - nextcloud-db
    networks:
      - proxy
      - cloud
    ports:
      - 3000:80
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:cloud.kevily.net
      - traefik.port=3000
        
networks:
  proxy:
    external: true
  cloud:
